service: "nihongo-users"
custom:
  tableName: "users-table-${self:provider.stage}"

provider:
  name: "aws"
  runtime: "nodejs10.x"
  stage: "dev"
  region: "eu-west-1"

functions:
  registerUser:
    handler: api/userHandler.registerUser
    events:
      - http:
          method: POST
          path: /register
          private: false
  authenticateUser:
    handler: api/userHandler.authenticateUser
    events:
      - http:
          method: POST
          path: /authenticate
          private: false
  getUser:
    handler: api/userHandler.getUser
    events:
      - http:
          method: GET
          path: /getUser
          private: false
  getAllUsers:
    handler: api/userHandler.getAllUsers
    events:
      - http:
          method: GET
          path: /getAllUsers
          private: false
  deleteUser:
    handler: api/userHandler.deleteUser
    events:
      - http:
          method: POST
          path: /deleteUser
          private: false

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
