service: "nihongo-kanji"
custom:
  tableName: "kanji-table-${self:provider.stage}"
provider:
  name: "aws"
  runtime: "nodejs10.x"
  stage: "dev"
  region: "eu-west-1"
functions:
  postKanji:
    handler: api/kanjiHandler.postKanji
    events:
      - http:
          method: POST
          path: /postKanji
          private: false
  getAllN5Kanji:
    handler: api/kanjiHandler.getAllN5Kanji
    events:
      - http:
          method: GET
          path: /getAllN5Kanji
          private: false

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: kanjiTable
        AttributeDefinitions:
          - AttributeName: kanji
            AttributeType: S
          - AttributeName: grade
            AttributeType: S
        KeySchema:
          - AttributeName: kanji
            KeyType: HASH
            # the primary can be just the partition key, i.e. the HASH key, or a combination of HASH and RANGE (partition and)
          - AttributeName: grade
            KeyType: RANGE
            # RANGE = sort key
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
